name: java ci
run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "corretto" # See 'Supported distributions' for available options
          java-version: "21"
          cache: 'maven'
          
      - name: Test with Maven
        run: mvn -B test

  package:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "corretto" # See 'Supported distributions' for available options
          java-version: "21"
          cache: 'maven'
          
      - name: Build with Maven
        run: mvn -B package -Dmaven.test.skip
      - uses: actions/upload-artifact@v4
        with:
          name: dogapi-1.0-SNAPSHOT.jar
          path: target/dogapi-1.0-SNAPSHOT.jar

  release:
    name: release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: dogapi-1.0-SNAPSHOT.jar
          name: Release ${{ github.ref_name }}
          body: |
            This is an automated release from a workflow.
          fail_on_unmatched_files: true
