name: java ci
run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'corretto' # See 'Supported distributions' for available options
        java-version: '21'
    - name: Build with Maven
      run: mvn -B package --file pom.xml